<script setup lang="ts">
import { NButton, NCard, NForm, NFormItem, NInputNumber, NPopconfirm, NRadio, NRadioGroup, NSelect, NSpace } from 'naive-ui'
import type { AppConfig, CloseBehavior } from '../../shared/types'

defineProps<{ config: AppConfig | null; currentVersion: string; checkingForUpdates: boolean; uninstalling: boolean; checkForUpdates: () => void; uninstallApp: () => void }>()
const emit = defineEmits<{ updateConfig: [input: Partial<AppConfig>]; closeBehavior: [value: CloseBehavior]; launchAtStartup: [value: boolean] }>()
</script>

<template>
  <section class="page-section settings-page"><div class="settings-layout"><n-card bordered class="settings-card" :title="$t('settings.appearance')"><n-form class="settings-form" label-placement="top"><div class="settings-form-grid"><n-form-item :label="$t('settings.theme')"><n-select :value="config?.themeMode" :options="[{ label: $t('settings.light'), value: 'light' }, { label: $t('settings.dark'), value: 'dark' }, { label: $t('settings.system'), value: 'system' }]" :placeholder="$t('settings.themePlaceholder')" @update:value="emit('updateConfig', { themeMode: $event })" /></n-form-item><n-form-item :label="$t('settings.language')"><n-select :value="config?.locale" :options="[{ label: '简体中文', value: 'zh-CN' }, { label: 'English', value: 'en-US' }]" :placeholder="$t('settings.languagePlaceholder')" @update:value="emit('updateConfig', { locale: $event })" /></n-form-item><n-form-item :label="$t('settings.companyReadValidityMonths')"><n-input-number :value="config?.companyReadValidityMonths" :min="1" :precision="0" :placeholder="$t('settings.companyReadValidityMonthsPlaceholder')" @update:value="emit('updateConfig', { companyReadValidityMonths: $event ?? 3 })" /></n-form-item><n-form-item class="settings-form-item-wide" :label="$t('settings.closeBehavior')"><n-radio-group :value="config?.closeBehavior" @update:value="emit('closeBehavior', $event as CloseBehavior)"><n-space wrap><n-radio value="tray">{{ $t('settings.minimizeToTray') }}</n-radio><n-radio value="quit">{{ $t('settings.quitDirectly') }}</n-radio></n-space></n-radio-group></n-form-item><n-form-item class="settings-form-item-wide" :label="$t('settings.launchAtStartup')"><n-radio-group :value="config?.launchAtStartup" @update:value="emit('launchAtStartup', $event as boolean)"><n-space wrap><n-radio :value="true">{{ $t('settings.enable') }}</n-radio><n-radio :value="false">{{ $t('settings.disable') }}</n-radio></n-space></n-radio-group></n-form-item></div></n-form></n-card><n-card bordered class="settings-card settings-update-card" :title="$t('settings.update')"><div class="settings-update-panel"><div class="settings-version-block"><span class="muted-text">{{ $t('settings.version') }}</span><strong>{{ currentVersion }}</strong></div><n-button :loading="checkingForUpdates" @click="checkForUpdates">{{ $t('settings.checkUpdate') }}</n-button></div></n-card><n-card bordered class="settings-card settings-danger-card" :title="$t('settings.dangerZone')"><div class="settings-danger-panel"><div class="settings-danger-copy"><strong>{{ $t('settings.uninstall') }}</strong><p>{{ $t('settings.uninstallDescription') }}</p></div><n-popconfirm :positive-text="$t('settings.uninstallConfirmButton')" :negative-text="$t('common.cancel')" @positive-click="uninstallApp"><template #trigger><n-button type="error" secondary :loading="uninstalling">{{ $t('settings.uninstall') }}</n-button></template>{{ $t('settings.uninstallWarning') }}</n-popconfirm></div></n-card></div></section>
</template>
