[package]
name = "jobtrail-bootstrap"
version = "0.5.0"
edition = "2021"
build = "build.rs"

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"
[lints.clippy]
undocumented_unsafe_blocks = "deny"

[dependencies]
anyhow = "1.0"
dirs = "6.0"
mslnk = "0.1"
rfd = "0.15"
roxmltree = "0.20"
semver = "1.0"
tempfile = "3"
winreg = "0.55"
base64 = "0.22"
winapi = { version = "0.3.9", features = ["commctrl", "fileapi", "handleapi", "libloaderapi", "processthreadsapi", "synchapi", "wingdi", "winbase", "winnt", "winuser"] }
[build-dependencies]
winres = "0.1.12"
