export const ERROR_CODES = {
  DISCOVERY_JOB_OFFLINE: {
    category: 'business',
    level: 'info',
    ui: true,
    translationKey: 'error.DISCOVERY_JOB_OFFLINE',
  },
  DISCOVERY_UNAVAILABLE: {
    category: 'business',
    level: 'warn',
    ui: true,
    translationKey: 'error.DISCOVERY_UNAVAILABLE',
  },
  DISCOVERY_FAILED: {
    category: 'business',
    level: 'warn',
    ui: true,
    translationKey: 'error.DISCOVERY_FAILED',
  },
  EXAM_INVALID: {
    category: 'validation',
    level: 'warn',
    ui: true,
    translationKey: 'error.EXAM_INVALID',
  },
  EXAM_COUNTS_TOO_SMALL: {
    category: 'business',
    level: 'warn',
    ui: true,
    translationKey: 'error.EXAM_COUNTS_TOO_SMALL',
  },
  EXAM_CONFLICT: {
    category: 'business',
    level: 'warn',
    ui: true,
    translationKey: 'error.EXAM_CONFLICT',
  },
  EXAM_NOT_FOUND: {
    category: 'business',
    level: 'warn',
    ui: true,
    translationKey: 'error.EXAM_NOT_FOUND',
  },
  EXAM_ALREADY_GRADING: {
    category: 'business',
    level: 'warn',
    ui: true,
    translationKey: 'error.EXAM_ALREADY_GRADING',
  },
  EXAM_UNAVAILABLE: {
    category: 'business',
    level: 'warn',
    ui: true,
    translationKey: 'error.EXAM_UNAVAILABLE',
  },
  VALIDATION_ERROR: {
    category: 'validation',
    level: 'warn',
    ui: true,
    translationKey: 'error.VALIDATION_ERROR',
  },
  BACKUP_SOURCE_INVALID: {
    category: 'persistence',
    level: 'warn',
    ui: true,
    translationKey: 'error.BACKUP_SOURCE_INVALID',
  },
  BACKUP_INVALID: {
    category: 'persistence',
    level: 'warn',
    ui: true,
    translationKey: 'error.BACKUP_INVALID',
  },
  BACKUP_VERSION_UNSUPPORTED: {
    category: 'persistence',
    level: 'warn',
    ui: true,
    translationKey: 'error.BACKUP_VERSION_UNSUPPORTED',
  },
  NOT_FOUND: { category: 'validation', level: 'warn', ui: true, translationKey: 'error.NOT_FOUND' },
  BUILTIN_DATA: {
    category: 'business',
    level: 'warn',
    ui: true,
    translationKey: 'error.BUILTIN_DATA',
  },
  STATUS_IN_USE: {
    category: 'business',
    level: 'warn',
    ui: true,
    translationKey: 'error.STATUS_IN_USE',
  },
  LAST_STATUS: {
    category: 'business',
    level: 'warn',
    ui: true,
    translationKey: 'error.LAST_STATUS',
  },
  RESUME_IN_USE: {
    category: 'business',
    level: 'warn',
    ui: true,
    translationKey: 'error.RESUME_IN_USE',
  },
  COMPANY_IN_USE: {
    category: 'business',
    level: 'warn',
    ui: true,
    translationKey: 'error.COMPANY_IN_USE',
  },
  INDUSTRY_IN_USE: {
    category: 'business',
    level: 'warn',
    ui: true,
    translationKey: 'error.INDUSTRY_IN_USE',
  },
  CATALOG_CONFLICT: {
    category: 'business',
    level: 'warn',
    ui: true,
    translationKey: 'error.CATALOG_CONFLICT',
  },
  CATALOG_VERSION_ROLLBACK: {
    category: 'business',
    level: 'warn',
    ui: true,
    translationKey: 'error.CATALOG_VERSION_ROLLBACK',
  },
  CATALOG_APP_UPDATE_REQUIRED: {
    category: 'business',
    level: 'warn',
    ui: true,
    translationKey: 'error.CATALOG_APP_UPDATE_REQUIRED',
  },
  CATALOG_UPDATE_IN_PROGRESS: {
    category: 'business',
    level: 'warn',
    ui: true,
    translationKey: 'error.CATALOG_UPDATE_IN_PROGRESS',
  },
  WEB_INVALID_URL: {
    category: 'network',
    level: 'warn',
    ui: true,
    translationKey: 'error.WEB_INVALID_URL',
  },
  WEB_BLOCKED: {
    category: 'network',
    level: 'warn',
    ui: true,
    translationKey: 'error.WEB_BLOCKED',
  },
  WEB_CANCELLED: {
    category: 'cancellation',
    level: 'info',
    ui: true,
    translationKey: 'error.WEB_CANCELLED',
  },
  WEB_UNSUPPORTED: {
    category: 'network',
    level: 'warn',
    ui: true,
    translationKey: 'error.WEB_UNSUPPORTED',
  },
  WEB_TOO_LARGE: {
    category: 'network',
    level: 'warn',
    ui: true,
    translationKey: 'error.WEB_TOO_LARGE',
  },
  WEB_INVALID_CURSOR: {
    category: 'network',
    level: 'warn',
    ui: true,
    translationKey: 'error.WEB_INVALID_CURSOR',
  },
  WEB_CURSOR_EXPIRED: {
    category: 'network',
    level: 'warn',
    ui: true,
    translationKey: 'error.WEB_CURSOR_EXPIRED',
  },
  AGENT_CANCELLED: {
    category: 'cancellation',
    level: 'info',
    ui: true,
    translationKey: 'error.AGENT_CANCELLED',
  },
  MCP_DISABLED: {
    category: 'business',
    level: 'warn',
    ui: false,
    translationKey: 'error.MCP_DISABLED',
  },
  CONFIRMATION_REQUIRED: {
    category: 'business',
    level: 'warn',
    ui: false,
    translationKey: 'error.CONFIRMATION_REQUIRED',
  },
  CONFIRMATION_UNSUPPORTED: {
    category: 'business',
    level: 'warn',
    ui: false,
    translationKey: 'error.CONFIRMATION_UNSUPPORTED',
  },
  AI_API_KEY_EMPTY: {
    category: 'model',
    level: 'error',
    ui: true,
    translationKey: 'error.AI_API_KEY_EMPTY',
  },
  EXAM_GRADING_FAILED: {
    category: 'model',
    level: 'error',
    ui: true,
    translationKey: 'error.EXAM_GRADING_FAILED',
  },
  PERSISTENCE_INVALID: {
    category: 'persistence',
    level: 'error',
    ui: true,
    translationKey: 'error.PERSISTENCE_INVALID',
  },
  PERSISTENCE_BUSY: {
    category: 'persistence',
    level: 'error',
    ui: true,
    translationKey: 'error.PERSISTENCE_BUSY',
  },
  PERSISTENCE_UNSUPPORTED: {
    category: 'persistence',
    level: 'error',
    ui: true,
    translationKey: 'error.PERSISTENCE_UNSUPPORTED',
  },
  PERSISTENCE_FAILED: {
    category: 'persistence',
    level: 'error',
    ui: true,
    translationKey: 'error.PERSISTENCE_FAILED',
  },
  BACKUP_FAILED: {
    category: 'persistence',
    level: 'error',
    ui: true,
    translationKey: 'error.BACKUP_FAILED',
  },
  FILE_IMPORT_FAILED: {
    category: 'persistence',
    level: 'error',
    ui: true,
    translationKey: 'error.FILE_IMPORT_FAILED',
  },
  FILE_OPEN_FAILED: {
    category: 'persistence',
    level: 'error',
    ui: true,
    translationKey: 'error.FILE_OPEN_FAILED',
  },
  DATABASE_ERROR: {
    category: 'persistence',
    level: 'error',
    ui: true,
    translationKey: 'error.DATABASE_ERROR',
  },
  CATALOG_DOWNLOAD_FAILED: {
    category: 'business',
    level: 'error',
    ui: true,
    translationKey: 'error.CATALOG_DOWNLOAD_FAILED',
  },
  CATALOG_ASSET_MISSING: {
    category: 'business',
    level: 'error',
    ui: true,
    translationKey: 'error.CATALOG_ASSET_MISSING',
  },
  CATALOG_TOO_LARGE: {
    category: 'business',
    level: 'error',
    ui: true,
    translationKey: 'error.CATALOG_TOO_LARGE',
  },
  CATALOG_HASH_MISMATCH: {
    category: 'business',
    level: 'error',
    ui: true,
    translationKey: 'error.CATALOG_HASH_MISMATCH',
  },
  CATALOG_INVALID: {
    category: 'business',
    level: 'error',
    ui: true,
    translationKey: 'error.CATALOG_INVALID',
  },
  WEB_TIMEOUT: {
    category: 'network',
    level: 'error',
    ui: true,
    translationKey: 'error.WEB_TIMEOUT',
  },
  WEB_UNAVAILABLE: {
    category: 'network',
    level: 'error',
    ui: true,
    translationKey: 'error.WEB_UNAVAILABLE',
  },
  WEB_BROWSER_UNAVAILABLE: {
    category: 'network',
    level: 'error',
    ui: true,
    translationKey: 'error.WEB_BROWSER_UNAVAILABLE',
  },
  WEB_PARSE_FAILED: {
    category: 'network',
    level: 'error',
    ui: true,
    translationKey: 'error.WEB_PARSE_FAILED',
  },
  INTERNAL_ERROR: {
    category: 'business',
    level: 'error',
    ui: true,
    translationKey: 'error.INTERNAL_ERROR',
  },
  CONFIG_INVALID: {
    category: 'persistence',
    level: 'error',
    ui: false,
    translationKey: 'error.CONFIG_INVALID',
  },
  CONFIG_VERSION_UNSUPPORTED: {
    category: 'persistence',
    level: 'error',
    ui: false,
    translationKey: 'error.CONFIG_VERSION_UNSUPPORTED',
  },
  DATABASE_VERSION_UNSUPPORTED: {
    category: 'persistence',
    level: 'error',
    ui: false,
    translationKey: 'error.DATABASE_VERSION_UNSUPPORTED',
  },
  AGENT_WORKER_UNAVAILABLE: {
    category: 'model',
    level: 'error',
    ui: true,
    translationKey: 'error.AGENT_WORKER_UNAVAILABLE',
  },
  AGENT_WORKER_EXITED: {
    category: 'model',
    level: 'error',
    ui: true,
    translationKey: 'error.AGENT_WORKER_EXITED',
  },
  AGENT_WORKER_START_FAILED: {
    category: 'model',
    level: 'error',
    ui: true,
    translationKey: 'error.AGENT_WORKER_START_FAILED',
  },
  SYSTEM_ERROR: {
    category: 'business',
    level: 'error',
    ui: false,
    translationKey: 'error.SYSTEM_ERROR',
  },
  PROCESS_EXITED: {
    category: 'business',
    level: 'error',
    ui: false,
    translationKey: 'error.PROCESS_EXITED',
  },
  PROCESS_ERROR: {
    category: 'business',
    level: 'error',
    ui: false,
    translationKey: 'error.PROCESS_ERROR',
  },
  UPDATE_VERIFY_FAILED: {
    category: 'business',
    level: 'error',
    ui: false,
    translationKey: 'error.UPDATE_VERIFY_FAILED',
  },
  DIAGNOSTICS_FAILED: {
    category: 'diagnostics',
    level: 'error',
    ui: true,
    translationKey: 'error.DIAGNOSTICS_FAILED',
  },
  DIAGNOSTICS_TRANSPORT_FAILED: {
    category: 'diagnostics',
    level: 'error',
    ui: false,
    translationKey: 'error.DIAGNOSTICS_TRANSPORT_FAILED',
  },
  DIAGNOSTICS_WRITE_FAILED: {
    category: 'diagnostics',
    level: 'error',
    ui: false,
    translationKey: 'error.DIAGNOSTICS_WRITE_FAILED',
  },
  DIAGNOSTICS_EXPORT_FAILED: {
    category: 'diagnostics',
    level: 'error',
    ui: true,
    translationKey: 'error.DIAGNOSTICS_EXPORT_FAILED',
  },
  DIAGNOSTICS_STRUCTURE_INVALID: {
    category: 'diagnostics',
    level: 'error',
    ui: false,
    translationKey: 'error.DIAGNOSTICS_STRUCTURE_INVALID',
  },
  DIAGNOSTICS_VERSION_UNSUPPORTED: {
    category: 'diagnostics',
    level: 'error',
    ui: false,
    translationKey: 'error.DIAGNOSTICS_VERSION_UNSUPPORTED',
  },
  DIAGNOSTICS_OVERFLOW: {
    category: 'diagnostics',
    level: 'error',
    ui: false,
    translationKey: 'error.DIAGNOSTICS_OVERFLOW',
  },
  EXAM_GRADING_TIMEOUT: {
    category: 'model',
    level: 'error',
    ui: false,
    translationKey: 'error.EXAM_GRADING_TIMEOUT',
  },
} as const

export type DiagnosticErrorCode = keyof typeof ERROR_CODES
export type AppErrorCode = {
  [K in DiagnosticErrorCode]: (typeof ERROR_CODES)[K]['ui'] extends true ? K : never
}[DiagnosticErrorCode]

export function knownErrorCode(value: unknown): value is DiagnosticErrorCode {
  return typeof value === 'string' && Object.hasOwn(ERROR_CODES, value)
}
