export type BuiltinCompanySeed = {
  name: string
  industryIds: number[]
  careerUrl: string | null
  aliases: string[]
}

export const BUILTIN_COMPANIES: BuiltinCompanySeed[] = [
  { name: '腾讯', industryIds: [1], careerUrl: 'https://join.qq.com/', aliases: ['Tencent'] },
  { name: '字节跳动', industryIds: [1], careerUrl: 'https://jobs.bytedance.com/', aliases: ['ByteDance'] },
  { name: '阿里巴巴', industryIds: [1], careerUrl: 'https://talent.alibaba.com/', aliases: ['阿里'] },
  { name: '蚂蚁集团', industryIds: [1], careerUrl: 'https://www.antgroup.com/careers', aliases: ['Ant Group'] },
  { name: '美团', industryIds: [1], careerUrl: 'https://zhaopin.meituan.com/', aliases: ['Meituan'] },
  { name: '京东', industryIds: [1], careerUrl: 'https://zhaopin.jd.com/', aliases: ['JD'] },
  { name: '百度', industryIds: [1], careerUrl: 'https://talent.baidu.com/', aliases: ['Baidu'] },
  { name: '快手', industryIds: [1], careerUrl: 'https://zhaopin.kuaishou.cn/', aliases: ['Kuaishou'] },
  { name: '小红书', industryIds: [1], careerUrl: 'https://job.xiaohongshu.com/', aliases: ['Xiaohongshu'] },
  { name: '哔哩哔哩', industryIds: [1], careerUrl: 'https://jobs.bilibili.com/', aliases: ['B站'] },
  { name: '网易', industryIds: [1], careerUrl: 'https://campus.163.com/', aliases: ['NetEase'] },
  { name: '拼多多', industryIds: [1], careerUrl: 'https://careers.pinduoduo.com/', aliases: ['PDD'] },
  { name: '滴滴', industryIds: [1], careerUrl: 'https://talent.didiglobal.com/', aliases: ['Didi'] },
  { name: '携程', industryIds: [1], careerUrl: 'https://jobs.ctrip.com/', aliases: ['Trip.com'] },
  { name: '米哈游', industryIds: [2], careerUrl: 'https://jobs.mihoyo.com/', aliases: ['HoYoverse'] },
  { name: '莉莉丝游戏', industryIds: [2], careerUrl: 'https://lilithgames.jobs.feishu.cn/', aliases: ['Lilith Games'] },
  { name: '鹰角网络', industryIds: [2], careerUrl: 'https://job.hypergryph.com/', aliases: ['Hypergryph'] },
  { name: '完美世界', industryIds: [2], careerUrl: 'https://zhaopin.wanmei.com/', aliases: ['Perfect World'] },
  { name: '库洛游戏', industryIds: [2], careerUrl: 'https://kurogame.com/', aliases: ['Kuro Games'] },
  { name: '科大讯飞', industryIds: [3], careerUrl: 'https://campus.iflytek.com/', aliases: ['iFLYTEK'] },
  { name: '智谱AI', industryIds: [3], careerUrl: 'https://www.zhipuai.cn/', aliases: ['Zhipu AI'] },
  { name: 'MiniMax', industryIds: [3], careerUrl: 'https://www.minimaxi.com/careers', aliases: ['稀宇科技'] },
  { name: '商汤科技', industryIds: [3], careerUrl: 'https://www.sensetime.com/', aliases: ['SenseTime'] },
  { name: '比亚迪', industryIds: [19], careerUrl: 'https://job.byd.com/', aliases: ['BYD'] },
  { name: '蔚来', industryIds: [19], careerUrl: 'https://nio.com/careers', aliases: ['NIO'] },
  { name: '理想汽车', industryIds: [19], careerUrl: 'https://careers.lixiang.com/', aliases: ['Li Auto'] },
  { name: '小鹏汽车', industryIds: [19], careerUrl: 'https://jobs.xiaopeng.com/', aliases: ['XPeng'] },
  { name: '小米', industryIds: [6], careerUrl: 'https://hr.xiaomi.com/', aliases: ['Xiaomi'] },
  { name: '华为', industryIds: [7], careerUrl: 'https://career.huawei.com/', aliases: ['Huawei'] },
  { name: '中兴通讯', industryIds: [7], careerUrl: 'https://job.zte.com.cn/', aliases: ['ZTE'] },
  { name: '联想', industryIds: [6], careerUrl: 'https://jobs.lenovo.com/', aliases: ['Lenovo'] },
  { name: '海尔', industryIds: [21], careerUrl: 'https://maker.haier.com/', aliases: ['Haier'] },
  { name: '宁德时代', industryIds: [20], careerUrl: 'https://www.catl.com/careers/', aliases: ['CATL'] },
  { name: '寒武纪', industryIds: [5], careerUrl: 'https://www.cambricon.com/', aliases: ['Cambricon'] },
  { name: '地平线', industryIds: [5], careerUrl: 'https://www.horizon.cc/', aliases: ['Horizon Robotics'] },
  { name: '英伟达', industryIds: [5], careerUrl: 'https://www.nvidia.com/en-us/about-nvidia/careers/', aliases: ['NVIDIA'] },
  { name: '微软', industryIds: [4], careerUrl: 'https://careers.microsoft.com/', aliases: ['Microsoft'] },
  { name: '谷歌', industryIds: [4], careerUrl: 'https://careers.google.com/', aliases: ['Google'] },
  { name: '亚马逊', industryIds: [4], careerUrl: 'https://www.amazon.jobs/', aliases: ['Amazon'] },
  { name: '得物', industryIds: [14], careerUrl: 'https://hr.dewu.com/', aliases: ['POIZON'] },
  { name: '唯品会', industryIds: [14], careerUrl: 'https://job.vip.com/', aliases: ['Vipshop'] },
  { name: '叮咚买菜', industryIds: [14], careerUrl: 'https://careers.dingdong-inc.com/', aliases: ['Dingdong'] },
  { name: '哈啰出行', industryIds: [26], careerUrl: 'https://hr.hellobike.com/', aliases: ['HelloBike'] },
  { name: '曹操出行', industryIds: [26], careerUrl: 'https://www.caocaokeji.cn/', aliases: ['Cao Cao Mobility'] },
  { name: '同程旅行', industryIds: [31], careerUrl: 'https://job.ly.com/', aliases: ['Tongcheng Travel'] },
  { name: '途虎养车', industryIds: [19], careerUrl: 'https://hr.tuhu.cn/', aliases: ['Tuhu'] },
  { name: 'SHEIN', industryIds: [40], careerUrl: 'https://careers.shein.com/', aliases: ['希音'] },
  { name: '货拉拉', industryIds: [25], careerUrl: 'https://www.huolala.cn/', aliases: ['Lalamove'] },
  { name: '菜鸟', industryIds: [25], careerUrl: 'https://talent.cainiao.com/', aliases: ['Cainiao'] },
  { name: '顺丰', industryIds: [25], careerUrl: 'https://hr.sf-express.com/', aliases: ['SF Express'] },
  { name: '牧原股份', industryIds: [38], careerUrl: 'https://www.muyuanfoods.com/', aliases: ['Muyuan'] },
  { name: '伊利', industryIds: [16], careerUrl: 'https://campus.yili.com/', aliases: ['Yili'] },
  { name: '海康威视', industryIds: [8], careerUrl: 'https://campus.hikvision.com/', aliases: ['Hikvision'] },
  { name: '大疆', industryIds: [8], careerUrl: 'https://www.dji.com/cn/careers', aliases: ['DJI'] },
  { name: '立讯精密', industryIds: [8], careerUrl: 'https://www.luxshare-ict.com/', aliases: ['Luxshare'] },
  { name: '隆基绿能', industryIds: [20], careerUrl: 'https://www.longi.com/cn/careers/', aliases: ['LONGi'] },
  { name: '远景能源', industryIds: [20], careerUrl: 'https://www.envision-group.com/careers', aliases: ['Envision'] },
  { name: '恒瑞医药', industryIds: [18], careerUrl: 'https://www.hengrui.com/join.html', aliases: ['Hengrui'] },
  { name: '招商银行', industryIds: [11], careerUrl: 'https://career.cmbchina.com/', aliases: ['CMB'] },
  { name: '360', industryIds: [1], careerUrl: 'https://hr.360.cn/hr/list', aliases: ['奇虎360'] },
  { name: '微博', industryIds: [1], careerUrl: 'https://career.sina.com.cn/campus-recruitment/sina/43536', aliases: ['Weibo'] },
  { name: '知乎', industryIds: [1], careerUrl: 'https://app.mokahr.com/campus-recruitment/zhihu/68321?locale=zh-CN#/jobs', aliases: ['Zhihu'] },
  { name: '搜狐', industryIds: [1], careerUrl: 'https://app.mokahr.com/social-recruitment/sohu/43256?locale=zh-CN#/jobs?page=1&anchorName=jobsList', aliases: ['Sohu'] },
  { name: '中国移动', industryIds: [7], careerUrl: 'https://job.10086.cn/', aliases: ['China Mobile'] },
  { name: '金山办公', industryIds: [4], careerUrl: 'https://join.wps.cn/', aliases: ['WPS'] },
  { name: '迅雷', industryIds: [4], careerUrl: 'https://career.xunlei.com/', aliases: ['Xunlei'] },
  { name: '云从科技', industryIds: [3], careerUrl: 'http://jobs.cloudwalk.com/apply/cloudwalk/4871/#/', aliases: ['CloudWalk'] },
  { name: '旷视科技', industryIds: [3], careerUrl: 'http://zhaopin.megvii.com/', aliases: ['Megvii'] },
  { name: '依图科技', industryIds: [3], careerUrl: 'https://www.yitutech.com/cn/career?mode=social', aliases: ['YITU'] },
  { name: '甲骨文', industryIds: [4], careerUrl: 'https://www.oracle.com/cn/careers/', aliases: ['Oracle'] },
  { name: 'SAP', industryIds: [4], careerUrl: 'https://jobs.sap.com/?locale=zh_CN', aliases: ['思爱普'] },
  { name: 'IBM', industryIds: [4], careerUrl: 'https://www.ibm.com/cn-zh/careers/', aliases: ['国际商业机器'] },
  { name: '爱奇艺', industryIds: [32], careerUrl: 'https://zhaopin.iqiyi.com/', aliases: ['iQIYI'] },
  { name: '英特尔', industryIds: [5], careerUrl: 'https://chinacampus.jobs.intel.cn/intel/position/index?recruitmentType=CAMPUSRECRUITMENT', aliases: ['Intel'] },
  { name: 'AMD', industryIds: [5], careerUrl: 'https://careers.amd.com/jobs?country=China&page=1', aliases: ['超威半导体'] },
  { name: '高通', industryIds: [5], careerUrl: 'https://www.qualcomm.cn/company/careers', aliases: ['Qualcomm'] },
  { name: '台积电', industryIds: [5], careerUrl: 'https://careers.tsmc.com/en_US/careers', aliases: ['TSMC'] },
  { name: '中芯国际', industryIds: [5], careerUrl: 'https://smics.zhiye.com/social', aliases: ['SMIC'] },
  { name: '荣耀', industryIds: [6], careerUrl: 'https://www.honor.com/cn/career/', aliases: ['HONOR'] },
  { name: 'OPPO', industryIds: [6], careerUrl: 'https://careers.oppo.com/university/oppo/', aliases: ['欧珀'] },
  { name: 'vivo', industryIds: [6], careerUrl: 'https://hr.vivo.com/', aliases: ['维沃'] },
  { name: '京东方', industryIds: [8], careerUrl: 'https://campus.boe.com/#/jobs', aliases: ['BOE'] },
  { name: 'TCL', industryIds: [8], careerUrl: 'https://zhaopin.tcl.com/', aliases: ['TCL科技'] },
  { name: '传音控股', industryIds: [6], careerUrl: 'https://transsion.zhiye.com/', aliases: ['Transsion'] },
  { name: '安克创新', industryIds: [8], careerUrl: 'https://career.anker.com.cn/', aliases: ['Anker'] },
  { name: '美的集团', industryIds: [21], careerUrl: 'https://recruit.midea.com/recruitOut/ihr/home/index', aliases: ['Midea'] },
  { name: '格力电器', industryIds: [21], careerUrl: 'https://zhaopin.greeyun.com/home', aliases: ['Gree'] },
  { name: '海信', industryIds: [21], careerUrl: 'https://jobs.hisense.com/', aliases: ['Hisense'] },
  { name: '吉利汽车', industryIds: [19], careerUrl: 'https://campus.geely.com/campus-recruitment/geely/78436/#/jobs', aliases: ['Geely'] },
  { name: '长城汽车', industryIds: [19], careerUrl: 'https://zhaopin.gwm.cn/', aliases: ['GWM'] },
  { name: '中国电信', industryIds: [7], careerUrl: 'https://job.chinatelecom.com.cn/wt/TELE/web/index', aliases: ['China Telecom'] },
  { name: '上汽集团', industryIds: [19], careerUrl: 'https://www.saicmotor.com/chinese/rlzy/index.html', aliases: ['SAIC'] },
  { name: '赛力斯', industryIds: [19], careerUrl: 'https://www.seres.cn/p/career-development.html', aliases: ['SERES'] },
  { name: '国轩高科', industryIds: [20], careerUrl: 'https://gotion.zhiye.com/', aliases: ['Gotion High-tech'] },
  { name: '阳光电源', industryIds: [20], careerUrl: 'https://jobs.sungrowpower.com/', aliases: ['Sungrow'] },
  { name: '亿纬锂能', industryIds: [20], careerUrl: 'https://www.evebattery.com/join-us', aliases: ['EVE Energy'] },
  { name: '天合光能', industryIds: [20], careerUrl: 'https://app.mokahr.com/social-recruitment/trinasolar/98958#/', aliases: ['Trina Solar'] },
  { name: '新东方', industryIds: [30], careerUrl: 'https://zhaopin.xdf.cn/', aliases: ['New Oriental'] },
  { name: '中国工商银行', industryIds: [11], careerUrl: 'https://job.icbc.com.cn/pc/index.html', aliases: ['ICBC'] },
  { name: '中国建设银行', industryIds: [11], careerUrl: 'https://job2.ccb.com/cn/job/index.html', aliases: ['CCB'] },
  { name: '中国银行', industryIds: [11], careerUrl: 'https://www.boc.cn/aboutboc/bi4/', aliases: ['BOC'] },
  { name: '交通银行', industryIds: [11], careerUrl: 'https://job.bankcomm.com/#/', aliases: ['Bank of Communications'] },
  { name: '中国平安', industryIds: [13], careerUrl: 'https://www.pingan.com/official/recruitment', aliases: ['Ping An'] },
  { name: '中信证券', industryIds: [12], careerUrl: 'https://careers.citics.com/', aliases: ['CITIC Securities'] },
  { name: '东方财富', industryIds: [10], careerUrl: 'https://zhaopin.eastmoney.com/', aliases: ['Eastmoney'] },
  { name: '蒙牛', industryIds: [16], careerUrl: 'https://mengniu.zhiye.com/custom/index', aliases: ['Mengniu'] },
  { name: '宝洁', industryIds: [15], careerUrl: 'https://careers.pg.com.cn/cn/zh/home', aliases: ['P&G'] },
  { name: '联合利华', industryIds: [15], careerUrl: 'https://careers.unilever.com/en/location/china-jobs/34155/1814991/2', aliases: ['Unilever'] },
  { name: '普华永道', industryIds: [35], careerUrl: 'https://www.pwccn.com/zh/careers.html', aliases: ['PwC'] },
  { name: '腾讯音乐', industryIds: [1], careerUrl: 'https://join.tencentmusic.com/', aliases: ['TME'] },
  { name: '得到', industryIds: [30], careerUrl: 'https://dedao.jobs.feishu.cn/shezhao', aliases: ['Dedao'] },
  { name: '百川智能', industryIds: [3], careerUrl: 'https://careers.baichuan-inc.com/', aliases: ['Baichuan AI'] },
  { name: '月之暗面', industryIds: [3], careerUrl: 'https://careers.kimi.com/', aliases: ['Moonshot AI'] },
  { name: '壁仞科技', industryIds: [5], careerUrl: 'https://www.birentech.com/join/', aliases: ['Biren Technology'] },
  { name: '新华三集团', industryIds: [9], careerUrl: 'https://career.h3c.com/h3c/home/index', aliases: ['H3C'] },
  { name: '浪潮集团', industryIds: [9], careerUrl: 'http://career.inspur.com/campus2027/index.html', aliases: ['Inspur'] },
  { name: '中科创达', industryIds: [4], careerUrl: 'https://www.thundersoft.com/join-us/', aliases: ['ThunderSoft'] },
  { name: '新紫光集团', industryIds: [9], careerUrl: 'https://www.unigroup.com.cn/Join-Us/join.html', aliases: ['Unigroup'] },
  { name: '长江存储', industryIds: [5], careerUrl: 'https://www.ymtc.com/cn/joinus.html', aliases: ['YMTC'] },
  { name: '兆易创新', industryIds: [5], careerUrl: 'https://www.gigadevice.com.cn/about/career', aliases: ['GigaDevice'] },
  { name: '中微公司', industryIds: [5], careerUrl: 'https://www.amec-inc.com/index/Lists/index/catid/100.html', aliases: ['AMEC'] },
  { name: '广汽集团', industryIds: [19], careerUrl: 'https://gacrnd.zhiye.com/jobs', aliases: ['GAC'] },
  { name: '中国一汽', industryIds: [19], careerUrl: 'https://faw-zhaopin.hotjob.cn/', aliases: ['FAW'] },
  { name: '东风汽车', industryIds: [19], careerUrl: 'https://www.dfmc.com.cn/zhaopin/xiaoyuanzhaopin.html', aliases: ['Dongfeng'] },
  { name: '零跑汽车', industryIds: [19], careerUrl: 'https://leapmotor.zhiye.com/social', aliases: ['Leapmotor'] },
  { name: '中国人寿', industryIds: [13], careerUrl: 'https://chinalife.zhiye.com/custom/index', aliases: ['China Life'] },
  { name: '中国人民保险', industryIds: [13], careerUrl: 'https://picc.zhiye.com/custom/index', aliases: ['PICC'] },
  { name: '中国太平洋保险', industryIds: [13], careerUrl: 'https://www.cpic.com.cn/aboutUs/rlzy/ygzp/', aliases: ['CPIC'] },
  { name: '中金公司', industryIds: [12], careerUrl: 'https://cicc.zhiye.com/custom/campusdt?hideMenu=1', aliases: ['CICC'] },
  { name: '华泰证券', industryIds: [12], careerUrl: 'https://wecruit.hotjob.cn/SU6013d14e5d83dc11e4a8ae4d/pb/index', aliases: ['Huatai Securities'] },
  { name: '广发证券', industryIds: [12], careerUrl: 'https://job.gf.com.cn/', aliases: ['GF Securities'] },
  { name: '中信银行', industryIds: [11], careerUrl: 'https://job.citicbank.com/', aliases: ['China CITIC Bank'] },
  { name: '民生银行', industryIds: [11], careerUrl: 'https://career.cmbc.com.cn/', aliases: ['CMBC'] },
  { name: '迈瑞医疗', industryIds: [17], careerUrl: 'https://www.mindray.com/cn/career', aliases: ['Mindray'] },
  { name: '联影医疗', industryIds: [17], careerUrl: 'https://global.united-imaging.com/zh-cn/careers', aliases: ['United Imaging'] },
  { name: '药明康德', industryIds: [18], careerUrl: 'https://wuxiapptec.zhiye.com/jobs', aliases: ['WuXi AppTec'] },
  { name: '复星医药', industryIds: [18], careerUrl: 'https://www.fosunpharma.com/careers/', aliases: ['Fosun Pharma'] },
  { name: '百济神州', industryIds: [18], careerUrl: 'https://www.beonemedicines.com.cn/careers/', aliases: ['BeiGene'] },
  { name: '泡泡玛特', industryIds: [15], careerUrl: 'https://popmart.zhiye.com/', aliases: ['POP MART'] },
  { name: '名创优品', industryIds: [15], careerUrl: 'https://miniso.zhiye.com/', aliases: ['MINISO'] },
  { name: '喜茶', industryIds: [16], careerUrl: 'https://heytea.zhiye.com/', aliases: ['HEYTEA'] },
  { name: '元气森林', industryIds: [16], careerUrl: 'https://k11pnjpvz1.jobs.feishu.cn/index', aliases: ['Genki Forest'] },
  { name: '李宁', industryIds: [15], careerUrl: 'https://lining.hotjob.cn/', aliases: ['Li-Ning'] },
  { name: '安踏', industryIds: [15], careerUrl: 'https://jobs.anta.com/', aliases: ['ANTA'] },
  { name: '百胜中国', industryIds: [16], careerUrl: 'https://yumchina.zhiye.com/alljob?c=1', aliases: ['Yum China'] },
  { name: '中国石油', industryIds: [28], careerUrl: 'https://www.cnpc.com.cn/cnpc/jrwm/jrwm_index.shtml', aliases: ['CNPC'] },
  { name: '中国石化', industryIds: [28], careerUrl: 'https://job.sinopec.com/', aliases: ['Sinopec'] },
  { name: '国家电网', industryIds: [29], careerUrl: 'https://zhaopin.sgcc.com.cn/sgcchr/static/home.html', aliases: ['State Grid'] },
  { name: '南方电网', industryIds: [29], careerUrl: 'https://zhaopin.csg.cn/', aliases: ['China Southern Power Grid'] },
  { name: '中国国航', industryIds: [27], careerUrl: 'https://zhaopin.airchina.com.cn/cn/about_us/recruitment/index.shtml', aliases: ['Air China'] },
  { name: '南方航空', industryIds: [27], careerUrl: 'https://job.csair.com/', aliases: ['China Southern Airlines'] },
  { name: '东方航空', industryIds: [27], careerUrl: 'https://job.ceair.com/', aliases: ['China Eastern'] },
  { name: '华住集团', industryIds: [31], careerUrl: 'https://campus.hworld.com/', aliases: ['H World'] },
  { name: '贝壳', industryIds: [23], careerUrl: 'https://campus.ke.com/', aliases: ['KE Holdings'] },
  { name: '龙湖集团', industryIds: [23], careerUrl: 'https://www.longfor.com/join/job.html', aliases: ['Longfor'] },
  { name: '喜马拉雅', industryIds: [32], careerUrl: 'https://jobs.ximalaya.com/', aliases: ['Ximalaya'] },
  { name: 'Keep', industryIds: [41], careerUrl: 'https://www.calorietech.com/join', aliases: ['卡路里科技'] },
  { name: 'Soul', industryIds: [1], careerUrl: 'https://www.soulapp.cn/career', aliases: ['Soul App'] },
  { name: '云天励飞', industryIds: [3], careerUrl: 'https://www.intellif.com/int/join.html', aliases: ['Intellifusion'] },
  { name: '中国邮政', industryIds: [25], careerUrl: 'https://chinapostshzp.zhaopin.com/', aliases: ['China Post'] },
  { name: '中国铁路', industryIds: [26], careerUrl: 'https://rczp.china-railway.com.cn/page/recruitment/rec_info.html', aliases: ['China Railway'] },
  { name: '中国建筑', industryIds: [23], careerUrl: 'https://www.cscec.com/rlzy_new/rczp/', aliases: ['CSCEC'] },
  { name: '中国交建', industryIds: [23], careerUrl: 'https://zhaopin.ccccltd.cn/', aliases: ['CCCC'] },
  { name: '中国中铁', industryIds: [23], careerUrl: 'https://www.crecg.com/web/rlzy65/rczp11/index.html', aliases: ['CREC'] },
  { name: '中国铁建', industryIds: [23], careerUrl: 'https://ztjs.hotjob.cn/', aliases: ['CRCC'] },
  { name: '华大基因', industryIds: [18], careerUrl: 'https://genomics.zhiye.com/', aliases: ['BGI'] },
  { name: '德邦快递', industryIds: [25], careerUrl: 'https://deppon.zhiye.com/campus', aliases: ['Deppon'] },
  { name: '三一集团', industryIds: [21], careerUrl: 'https://www.sanygroup.com/join/', aliases: ['SANY'] },
  { name: '徐工集团', industryIds: [21], careerUrl: 'https://www.xcmg.com/aboutus/job_center.htm', aliases: ['XCMG'] },
  { name: '中联重科', industryIds: [21], careerUrl: 'https://wecruit.hotjob.cn/SU60a6449a2f9d2430fdc11a19/pb/news.html?pageType=0', aliases: ['Zoomlion'] },
  { name: '微创医疗', industryIds: [17], careerUrl: 'https://www.microport.com.cn/join/index.html', aliases: ['MicroPort'] },
  { name: '中国核电', industryIds: [28], careerUrl: 'https://cnnc.zhiye.com/custom/index', aliases: ['CNNP'] },
  { name: '国家能源集团', industryIds: [28], careerUrl: 'https://zhaopin.chnenergy.com.cn/recTypeSerch?kinds=3', aliases: ['CHN Energy'] },
  { name: '中国海油', industryIds: [28], careerUrl: 'https://www.cnooc.com.cn/zyzx/', aliases: ['CNOOC'] },
  { name: '浦发银行', industryIds: [11], careerUrl: 'https://job.spdb.com.cn/', aliases: ['SPDB'] },
  { name: '兴业银行', industryIds: [11], careerUrl: 'https://job.cib.com.cn/portal/', aliases: ['CIB'] },
  { name: '光大银行', industryIds: [11], careerUrl: 'https://eoap.cebbank.com/uiap/wt/CEB/zpzh/home', aliases: ['China Everbright Bank'] },
  { name: '北京银行', industryIds: [11], careerUrl: 'https://bankofbeijing.zhiye.com/social', aliases: ['Bank of Beijing'] },
  { name: '宁波银行', industryIds: [11], careerUrl: 'https://zhaopin.nbcb.com.cn/app/', aliases: ['Ningbo Bank'] },
  { name: '招商证券', industryIds: [12], careerUrl: 'https://wecruit.hotjob.cn/SU629dbc0c0dcad452299bc0f7/pb/custom.html?parentKey=section_4&pageType=customize_section_4', aliases: ['CMS'] },
  { name: '中信建投', industryIds: [12], careerUrl: 'https://csc108.zhiye.com/campus/jobs', aliases: ['CITIC Securities'] },
  { name: '国信证券', industryIds: [12], careerUrl: 'https://guosen.zhiye.com/Social', aliases: ['Guosen'] },
  { name: '中国太平', industryIds: [13], careerUrl: 'https://cntaiping.zhiye.com/', aliases: ['China Taiping'] },
  { name: '首都机场', industryIds: [26], careerUrl: 'https://www.cah.com.cn/Information/Recruit/', aliases: ['Capital Airport'] },
  { name: '上海机场', industryIds: [26], careerUrl: 'https://www.shanghaiairport.com/shzp/index.html', aliases: ['Shanghai Airport'] },
  { name: '星巴克中国', industryIds: [15], careerUrl: 'https://www.starbucks.com.cn/about/careers', aliases: ['Starbucks China'] },
  { name: '麦当劳中国', industryIds: [15], careerUrl: 'http://officehire.mcdonalds.com.cn/apply/mcdchina/4327/#/', aliases: ["McDonald's China"] },
  { name: '百事中国', industryIds: [16], careerUrl: 'https://pepsico.51job.com/', aliases: ['PepsiCo China'] },
  { name: '中粮可口可乐', industryIds: [16], careerUrl: 'https://cofcoko.zhiye.com/', aliases: ['COFCO Coca-Cola'] },
  { name: '苏宁易购', industryIds: [14], careerUrl: 'https://careers.suning.cn/rps-web/', aliases: ['Suning'] },
  { name: '华润万家', industryIds: [14], careerUrl: 'https://wecruit.hotjob.cn/SU61500b08bef57c54dcc07957/pb/social.html', aliases: ['China Resources Vanguard'] },
  { name: '周大福', industryIds: [15], careerUrl: 'https://hr.ctf.com.cn/', aliases: ['Chow Tai Fook'] },
  { name: '锦江酒店', industryIds: [31], careerUrl: 'https://www.ivvajob.com/base/jinjianghotels', aliases: ['Jinjiang Hotels'] },
  { name: '首旅酒店', industryIds: [31], careerUrl: 'https://www.btg.com.cn/newsList/31/1.html', aliases: ['BTG'] },
  { name: '万科', industryIds: [23], careerUrl: 'https://www.vanke.com/join/talent', aliases: ['Vanke'] },
  { name: '保利发展', industryIds: [23], careerUrl: 'https://polycareer.zhiye.com/', aliases: ['Poly Developments'] },
  { name: '招商蛇口', industryIds: [23], careerUrl: 'https://cmsk1979.zhiye.com/', aliases: ['China Merchants Shekou'] },
  { name: '华润置地', industryIds: [23], careerUrl: 'https://crc.wintalent.cn/wt/CRC/web/index/CompCRCPageindex', aliases: ['CR Land'] },
  { name: '中国中车', industryIds: [21], careerUrl: 'https://crrc.hotjob.cn/', aliases: ['CRRC'] },
  { name: '中国兵器工业集团', industryIds: [21], careerUrl: 'https://norincogroupzhaopin.zhiye.com/', aliases: ['NORINCO'] },
  { name: '中国船舶集团', industryIds: [21], careerUrl: 'https://cssc.zhiye.com/', aliases: ['CSSC'] },
  { name: '中国航空工业集团', industryIds: [27], careerUrl: 'https://www.avic.com.cn/sycd/rczp/', aliases: ['AVIC'] },
  { name: '中国航天科技集团', industryIds: [27], careerUrl: 'https://www.spacetalent.com.cn/', aliases: ['CASC'] },
  { name: '中国航天科工集团', industryIds: [27], careerUrl: 'https://casicjob.iguopin.com/', aliases: ['CASIC'] },
  { name: '中国电子科技集团', industryIds: [8], careerUrl: 'https://cetc.iguopin.com/job', aliases: ['CETC'] },
  { name: '中国黄金集团', industryIds: [28], careerUrl: 'https://www.chinagoldgroup.com/zghj/rlzy/zczp/A080008001Gone1.html', aliases: ['China Gold'] },
  { name: '中国铝业集团', industryIds: [28], careerUrl: 'https://chinalco.iguopin.com/', aliases: ['CHINALCO'] },
  { name: '中国五矿', industryIds: [28], careerUrl: 'https://wecruit.hotjob.cn/SU62f37858bef57c29ead8adab/pb/index.html', aliases: ['Minmetals'] },
  { name: '中国宝武', industryIds: [21], careerUrl: 'https://baowugroup-zhaopin.51job.com/index05.html', aliases: ['Baowu'] },
  { name: '中国农业银行', industryIds: [11], careerUrl: 'https://career.abchina.com/build/index.html', aliases: ['ABC'] },
  { name: '中国邮政储蓄银行', industryIds: [11], careerUrl: 'https://www.psbc.com/cn/gyyc/rczp/shzp/', aliases: ['PSBC'] },
  { name: '浙商银行', industryIds: [11], careerUrl: 'https://zp.czbank.com.cn/zpweb/', aliases: ['CZBank'] },
  { name: '广发银行', industryIds: [11], careerUrl: 'https://www.cgbchina.com.cn/career/gonggao.jsp', aliases: ['CGB'] },
  { name: '同花顺', industryIds: [10], careerUrl: 'https://job.10jqka.com.cn/', aliases: ['10JQKA'] },
  { name: '金蝶', industryIds: [4], careerUrl: 'https://campus.kingdee.com/', aliases: ['Kingdee'] },
  { name: '恒生电子', industryIds: [4], careerUrl: 'https://hundsun.zhiye.com/', aliases: ['Hundsun'] },
  { name: '东软', industryIds: [4], careerUrl: 'https://www.neusoft.com/cn/about/job/', aliases: ['Neusoft'] },
  { name: '深信服', industryIds: [9], careerUrl: 'https://hr.sangfor.com/', aliases: ['Sangfor'] },
  { name: '汇川技术', industryIds: [21], careerUrl: 'https://recruit.inovance.com/jobs', aliases: ['Inovance'] },
  { name: '中航光电', industryIds: [8], careerUrl: 'https://www.jonhon.cn/job/talent.htm', aliases: ['JONHON'] },
  { name: '国药集团', industryIds: [18], careerUrl: 'https://www.sinopharm.com/recruitment.html', aliases: ['Sinopharm'] },
  { name: '华熙生物', industryIds: [18], careerUrl: 'https://www.hotjob.cn/wt/HXSW/web/index?brandCode=1', aliases: ['Bloomage'] },
  { name: '科伦药业', industryIds: [18], careerUrl: 'https://kelun.zhiye.com/', aliases: ['Kelun'] },
  { name: '石药集团', industryIds: [18], careerUrl: 'https://www.e-cspc.com/hr/index.html', aliases: ['CSPC'] },
  { name: '贝达药业', industryIds: [18], careerUrl: 'https://bettapharma.zhiye.com/', aliases: ['Betta Pharma'] },
  { name: '片仔癀', industryIds: [18], careerUrl: 'https://www.zzpzh.com/rczp/list_252.aspx', aliases: ['Pien Tze Huang'] },
  { name: '康龙化成', industryIds: [18], careerUrl: 'https://www.pharmaron.cn/careers', aliases: ['Pharmaron'] },
  { name: '永辉超市', industryIds: [14], careerUrl: 'https://www.yonghui.com.cn/html/web/rencaizhongxin/gongzuojihui/index.html', aliases: ['Yonghui'] },
  { name: '沃尔玛中国', industryIds: [14], careerUrl: 'https://walmartchina.avature.cn/zh_CN/careers', aliases: ['Walmart China'] },
  { name: '宜家中国', industryIds: [14], careerUrl: 'https://jobs.ikeachina.cn/', aliases: ['IKEA China'] },
  { name: '华夏银行', industryIds: [11], careerUrl: 'https://wecruit.hotjob.cn/SU645b0d18bef57c0907e9fbc8/pb/school.html', aliases: ['Huaxia Bank'] },
  { name: '平安银行', industryIds: [11], careerUrl: 'https://wetalent.pingan.com/cb3685e9c6163b7cb82ea4352291031e/campus/home', aliases: ['Ping An Bank'] },
  { name: '用友', industryIds: [4], careerUrl: 'https://career.yonyou.com/', aliases: ['Yonyou'] },
  { name: '中科曙光', industryIds: [9], careerUrl: 'https://sugon.zhiye.com/', aliases: ['Sugon'] },
  { name: '潍柴动力', industryIds: [21], careerUrl: 'https://weichai.zhiye.com/custom/index', aliases: ['Weichai'] },
  { name: '中国重汽', industryIds: [19], careerUrl: 'https://zhaopin.sinotruk.com:8009/', aliases: ['Sinotruk'] },
  { name: '长安汽车', industryIds: [19], careerUrl: 'https://changan.zhiye.com/Campus', aliases: ['Changan'] },
  { name: '奇瑞汽车', industryIds: [19], careerUrl: 'https://chery.zhiye.com/Campus', aliases: ['Chery'] },
  { name: '公牛集团', industryIds: [8], careerUrl: 'https://gongniu.zhiye.com/', aliases: ['BULL'] },
  { name: '中国华能', industryIds: [28], careerUrl: 'https://zhaopin.chng.com.cn/', aliases: ['CHNG'] },
  { name: '中国华电', industryIds: [28], careerUrl: 'https://rencaishichang.chd.com.cn/w3/', aliases: ['CHD'] },
  { name: '中国大唐', industryIds: [28], careerUrl: 'https://zhaopin.china-cdt.com/', aliases: ['China Datang'] },
  { name: '国家电投', industryIds: [28], careerUrl: 'https://spic2026.iguopin.com/', aliases: ['SPIC'] },
  { name: '中国核工业集团', industryIds: [28], careerUrl: 'https://cnnc.iguopin.com/job', aliases: ['CNNC'] },
  { name: '瑞幸咖啡', industryIds: [16], careerUrl: 'https://www.zhaopin.com/companydetail/jobs-CZ598313130/', aliases: ['Luckin Coffee'] },
  { name: '蜜雪冰城', industryIds: [16], careerUrl: 'https://careers.mxbc.com/', aliases: ['Mixue'] },
  { name: '大华股份', industryIds: [8], careerUrl: 'https://job.dahuatech.com/', aliases: ['Dahua'] },
  { name: '洽洽食品', industryIds: [16], careerUrl: 'https://qiaqiafood.zhiye.com/', aliases: ['Qiaqia'] },
  { name: '春秋航空', industryIds: [26], careerUrl: 'https://www.hotjob.cn/wt/springhr/mobweb/v8/index?brandCode=1&request_locale=zh_CN', aliases: ['Spring Airlines'] },
  { name: '吉祥航空', industryIds: [26], careerUrl: 'https://wecruit.hotjob.cn/SU62ea129d0dcad4075c8525ca/pb/index.html', aliases: ['Juneyao Air'] },
  { name: '国泰海通证券', industryIds: [12], careerUrl: 'https://sec-sh-offer.gtjaqh.com/', aliases: ['Guotai Haitong'] },
  { name: '安能物流', industryIds: [25], careerUrl: 'https://www.ane56.com/self-recruit.html', aliases: ['ANE'] },
  { name: '极兔速递', industryIds: [25], careerUrl: 'https://jtexpress.jobs.feishu.cn/index', aliases: ['J&T Express'] },
  { name: '韵达速递', industryIds: [25], careerUrl: 'https://yundaex.com/cn/hr_online.php', aliases: ['Yunda'] },
  { name: '三峡集团', industryIds: [28], careerUrl: 'https://www.ctg.com.cn/sxjt/rlzy71/rlzydt/2026042410005892280/index.html', aliases: ['CTG'] },
  { name: '中国节能环保集团', industryIds: [42], careerUrl: 'https://cecep.iguopin.com/job', aliases: ['CECEP'] },
  { name: '光明乳业', industryIds: [16], careerUrl: 'https://www.brightdairy.com/About/Join', aliases: ['Bright Dairy'] },
  { name: '涂鸦智能', industryIds: [8], careerUrl: 'https://job.tuya.com/', aliases: ['Tuya'] },
  { name: '九号公司', industryIds: [8], careerUrl: 'https://join.ninebot.com/campus', aliases: ['Ninebot'] },
  { name: '芯原股份', industryIds: [5], careerUrl: 'https://www.verisilicon.com/cn/Careers', aliases: ['VeriSilicon'] },
  { name: '中际旭创', industryIds: [8], careerUrl: 'https://www.zj-innolight.com/index/index/join.html', aliases: ['InnoLight'] },
  { name: '复旦微电子', industryIds: [5], careerUrl: 'https://www.fmsh.com/school/', aliases: ['Fudan Microelectronics'] },
  { name: '摩尔线程', industryIds: [5], careerUrl: 'https://www.mthreads.com/jobs', aliases: ['Moore Threads'] },
  { name: '沐曦股份', industryIds: [5], careerUrl: 'https://recruitment.metax-tech.com/', aliases: ['MetaX'] },
  { name: '云知声', industryIds: [3], careerUrl: 'https://unisound.com/careers', aliases: ['Unisound'] },
  { name: '出门问问', industryIds: [3], careerUrl: 'https://www.chumenwenwen.com/recruit/index', aliases: ['Mobvoi'] },
  { name: '科大国创', industryIds: [4], careerUrl: 'https://kdgcsoft.zhiye.com/campus/jobs', aliases: ['Keda Guochuang'] },
  { name: '思特威', industryIds: [5], careerUrl: 'https://www.smartsenstech.com/joinus', aliases: ['SmartSens'] },
  { name: '叠纸游戏', industryIds: [2], careerUrl: 'https://career.papegames.com/campus', aliases: ['PaperGames'] },
  { name: '巨人网络', industryIds: [2], careerUrl: 'http://hr.ztgame.com/campus/', aliases: ['Giant Interactive'] },
  { name: '三七互娱', industryIds: [2], careerUrl: 'https://37wan.zhiye.com/', aliases: ['37 Interactive'] },
  { name: '泰格医药', industryIds: [17], careerUrl: 'https://tigermed.zhiye.com/', aliases: ['Tigermed'] },
  { name: '信达生物', industryIds: [18], careerUrl: 'https://innoventbio.zhiye.com/Campus', aliases: ['Innovent'] },
  { name: '荣昌生物', industryIds: [18], careerUrl: 'https://www.remegen.cn/index.php?v=listing&cid=45', aliases: ['RemeGen'] },
  { name: '康希诺', industryIds: [18], careerUrl: 'https://cansinotech.zhiye.com/', aliases: ['CanSino'] },
  { name: '金域医学', industryIds: [17], careerUrl: 'https://kingmed.zhiye.com/', aliases: ['KingMed'] },
  { name: '扬子江药业', industryIds: [18], careerUrl: 'https://www.yangzijiang.com/Career', aliases: ['Yangtze River Pharmaceutical'] },
  { name: '白云山制药总厂', industryIds: [18], careerUrl: 'https://byszc.com/join-us/recruitment.html', aliases: ['BYS'] },
  { name: '海天味业', industryIds: [16], careerUrl: 'https://haday.hotjob.cn/', aliases: ['Haday'] },
  { name: '绝味食品', industryIds: [16], careerUrl: 'https://www.juewei.cn/page/resource/recruit.html', aliases: ['Juewei'] },
  { name: '新希望', industryIds: [38], careerUrl: 'https://newhope.zhiye.com/index?p=3^-1,1^7&day=-1&PageIndex=1&class=-1', aliases: ['New Hope'] },
  { name: '三花智控', industryIds: [21], careerUrl: 'https://www.zjshc.com/about/join.html', aliases: ['Sanhua'] },
  { name: '汇顶科技', industryIds: [5], careerUrl: 'http://goodix.zhiye.com/', aliases: ['Goodix'] },
  { name: '中国民航信息集团', industryIds: [26], careerUrl: 'https://travelsky.hotjob.cn/', aliases: ['TravelSky'] },
  { name: '中国远洋海运', industryIds: [26], careerUrl: 'https://coscoshipping.iguopin.com/job', aliases: ['COSCO SHIPPING'] },
  { name: '神州租车', industryIds: [41], careerUrl: 'https://zhaopin.zuche.com/', aliases: ['CAR Inc.'] },
  { name: '国金证券', industryIds: [12], careerUrl: 'https://www.gjzq.com.cn/career/index.html', aliases: ['Sinolink Securities'] },
  { name: '中国银河证券', industryIds: [12], careerUrl: 'https://chinastock.zhiye.com/', aliases: ['China Galaxy Securities'] },
  { name: '上海银行', industryIds: [11], careerUrl: 'https://bosc.zhiye.com/campus', aliases: ['Bank of Shanghai'] },
  { name: '国家开发银行', industryIds: [10], careerUrl: 'https://www.cdb.com.cn/xwzx/xxgg/zpgg/', aliases: ['CDB'] },
  { name: '中国进出口银行', industryIds: [10], careerUrl: 'https://zhaopin.eximbank.gov.cn/', aliases: ['China Exim Bank'] },
  { name: '中国农业发展银行', industryIds: [11], careerUrl: 'https://www.adbc.com.cn/n5/n15/c660492/content.html', aliases: ['ADBC'] },
  { name: '中国中免', industryIds: [14], careerUrl: 'https://www.ctgdutyfree.com.cn/shehuizhaopin.html', aliases: ['CDF'] },
  { name: '中国联通', industryIds: [7], careerUrl: 'https://www.chinaunicom.com.cn/46/menu01/528/column06', aliases: ['China Unicom'] },
  { name: '中国能建', industryIds: [21], careerUrl: 'https://zhaopin.ceec.net.cn/', aliases: ['China Energy Engineering'] },
  { name: '中国电建', industryIds: [21], careerUrl: 'https://zhaopin.powerchina.cn/', aliases: ['PowerChina'] },
  { name: '中国化学', industryIds: [21], careerUrl: 'https://cncec.iguopin.com/job', aliases: ['CNCEC'] },
  { name: '中国有色矿业集团', industryIds: [28], careerUrl: 'https://hrcnmc.iguopin.com/jobcampus', aliases: ['CNMC'] },
  { name: '中国建材集团', industryIds: [21], careerUrl: 'https://cnbmjob.iguopin.com/notice', aliases: ['CNBM'] },
  { name: '伊利股份', industryIds: [16], careerUrl: 'https://yili.hotjob.cn/', aliases: ['Yili'] },
  { name: '中国航空油料集团', industryIds: [26], careerUrl: 'https://cnaf.zhiye.com/Campus', aliases: ['CNAF'] },
  { name: '中国国新', industryIds: [35], careerUrl: 'https://www.crhc.cn/rcfz/rczp/A005007002index_1.htm', aliases: ['China Reform'] },
  { name: '青岛啤酒', industryIds: [16], careerUrl: 'https://tsingtao.zhiye.com/', aliases: ['Tsingtao'] },
  { name: '国投电力', industryIds: [29], careerUrl: 'https://sdicpower.iguopin.com/', aliases: ['SDIC Power'] },
  { name: '华润集团', industryIds: [35], careerUrl: 'https://crcjob.iguopin.com/job-campus', aliases: ['China Resources'] },
  { name: '新华保险', industryIds: [13], careerUrl: 'https://nci.zhiye.com/', aliases: ['New China Life'] },
  { name: '国元证券', industryIds: [12], careerUrl: 'https://gyzq.zhiye.com/', aliases: ['Guoyuan Securities'] },
  { name: '紫金矿业', industryIds: [28], careerUrl: 'https://join.zjky.cn', aliases: ['Zijin Mining'] },
  { name: '北京车之家信息技术有限公司', industryIds: [1], careerUrl: 'https://talent.autohome.com.cn/', aliases: ['Autohome', '汽车之家'] },
  { name: '新浪', industryIds: [32], careerUrl: 'https://www.sina.com.cn/recruit.shtml', aliases: ['Sina'] },
  { name: '北京豆网科技有限公司', industryIds: [32], careerUrl: 'https://jobs.douban.com/', aliases: ['Douban', '豆瓣'] },
  { name: '北京多氪信息科技有限公司', industryIds: [32], careerUrl: 'https://zhaopin.36kr.com/', aliases: ['36Kr', '36氪'] },
  { name: '北京值得买科技股份有限公司', industryIds: [14], careerUrl: 'https://zhidemai.jobs.feishu.cn/index', aliases: ['SMZDM', '什么值得买'] },
  { name: '凤凰新媒体有限公司', industryIds: [32], careerUrl: 'https://career.ifeng.com/', aliases: ['iFeng', '凤凰网'] },
  { name: '北京趣拿软件科技有限公司', industryIds: [31], careerUrl: 'https://hf7l9aiqzx.jobs.feishu.cn/704852', aliases: ['Qunar', '去哪儿'] },
  { name: '途家网网络技术（北京）有限公司', industryIds: [31], careerUrl: 'http://campus.tujia.com/', aliases: ['Tujia', '途家'] },
  { name: '车好多集团', industryIds: [19], careerUrl: 'https://wecruit.hotjob.cn/SU6474230c0dcad45af14d7963/pb/index.html', aliases: ['Guazi', '瓜子二手车'] },
  { name: '北京当当网信息技术有限公司', industryIds: [14], careerUrl: 'http://t.dangdang.com/join_us', aliases: ['Dangdang', '当当网'] },
  { name: '北京物美商业集团股份有限公司', industryIds: [14], careerUrl: 'https://wumart.jobs.feishu.cn/index/login', aliases: ['Wumart', '物美'] },
  { name: '多点生活（中国）网络科技有限公司', industryIds: [14], careerUrl: 'https://duodian.jobs.feishu.cn/dmall', aliases: ['Dmall', '多点DMALL'] },
  { name: '高途教育科技集团有限公司', industryIds: [30], careerUrl: 'https://job.gaotu.cn/', aliases: ['Gaotu', '高途'] },
  { name: '作业帮教育科技（北京）有限公司', industryIds: [30], careerUrl: 'https://job.zuoyebang.com/', aliases: ['Zuoyebang', '作业帮'] },
  { name: '北京猿辅导科技有限公司', industryIds: [30], careerUrl: 'https://hr.yuanfudao.com/', aliases: ['Yuanfudao', '猿辅导'] },
  { name: '北京世纪好未来教育科技有限公司', industryIds: [30], careerUrl: 'https://job.tal.com/', aliases: ['TAL Education', '好未来'] },
  { name: '北京火花思维教育科技有限公司', industryIds: [30], careerUrl: 'https://h5-sparkle.huohua.cn/recruit?source=xiaozhaokonhgzhongxjhui', aliases: ['Spark Education', '火花思维'] },
  { name: '北京纵情向前科技有限公司', industryIds: [13], careerUrl: 'https://jobs.waterdrop-inc.com/campus', aliases: ['Waterdrop', '水滴公司'] },
  { name: '宜信', industryIds: [10], careerUrl: 'https://wecruit.hotjob.cn/SU63f35dc6bef57c71d9fd08f8/pb/index.html', aliases: ['Creditease'] },
  { name: '度小满科技（北京）有限公司', industryIds: [10], careerUrl: 'https://campus.duxiaoman.com/', aliases: ['Duxiaoman', '度小满'] },
  { name: '北森控股有限公司', industryIds: [37], careerUrl: 'https://beisen.zhiye.com/', aliases: ['Beisen', '北森'] },
  { name: '北京明略昭辉科技有限公司', industryIds: [3], careerUrl: 'https://mininglamp.zhiye.com/', aliases: ['Mininglamp', '明略科技'] },
  { name: '奇安信科技集团股份有限公司', industryIds: [9], careerUrl: 'https://campus.qianxin.com/', aliases: ['Qianxin', '奇安信'] },
  { name: '北京金山云网络技术有限公司', industryIds: [4], careerUrl: 'https://jssoft.zhiye.com/campus/jobs?silence=1', aliases: ['Kingsoft Cloud', '金山云'] },
  { name: '金山软件有限公司', industryIds: [4], careerUrl: 'https://www.kingsoft.com/iksnet/recruit', aliases: ['Kingsoft', '金山软件'] },
  { name: '软通动力信息技术（集团）股份有限公司', industryIds: [9], careerUrl: 'https://career.isoftstone.com/', aliases: ['iSoftStone', '软通动力'] },
  { name: '神州数码集团股份有限公司', industryIds: [9], careerUrl: 'https://digitalchina.zhiye.com/Campus', aliases: ['Digital China', '神州数码'] },
  { name: '北京宇信科技集团股份有限公司', industryIds: [9], careerUrl: 'https://yusys-campus.zhiye.com/campus/', aliases: ['Yusys', '宇信科技'] },
  { name: '北京东方通科技股份有限公司', industryIds: [4], careerUrl: 'https://www.tongtech.com/recruit.html', aliases: ['TongTech', '东方通'] },
  { name: '北京华宇软件股份有限公司', industryIds: [4], careerUrl: 'https://thunisoft-group.zhiye.com/', aliases: ['Thunisoft', '华宇软件'] },
  { name: '北京君正集成电路股份有限公司', industryIds: [5], careerUrl: 'http://www.ingenic.com.cn/join', aliases: ['Ingenic', '北京君正'] },
  { name: '北京石头世纪科技有限公司', industryIds: [6], careerUrl: 'https://roborock.zhiye.com/', aliases: ['Roborock', '石头科技'] },
  { name: '北京万泰生物药业股份有限公司', industryIds: [18], careerUrl: 'https://jobs.yst.com.cn/campus', aliases: ['Wantai', '万泰生物'] },
  { name: '北京诺禾致源科技股份有限公司', industryIds: [17], careerUrl: 'https://novogene.zhiye.com/', aliases: ['Novogene', '诺禾致源'] },
  { name: '乐普（北京）医疗器械股份有限公司', industryIds: [17], careerUrl: 'https://hcm.lepu-crm.com/recruit', aliases: ['Lepu Medical', '乐普医疗'] },
  { name: '呷哺呷哺餐饮管理有限公司', industryIds: [16], careerUrl: 'http://60.205.147.215/Jobs/list.aspx', aliases: ['Xiabu', '呷哺呷哺'] },
  { name: '北京大北农科技集团股份有限公司', industryIds: [38], careerUrl: 'https://wecruit.hotjob.cn/SU66ab37a71c240e2e76256280/pb/index.html', aliases: ['DBN', '大北农'] },
  { name: '掌阅科技股份有限公司', industryIds: [32], careerUrl: 'https://q7w8vltyes.jobs.feishu.cn/2024', aliases: ['iReader', '掌阅科技'] },
  { name: '挚文集团', industryIds: [32], careerUrl: 'https://campus.hellogroup.com/', aliases: ['Momo', '陌陌'] },
  { name: '北京幻想纵横网络技术有限公司', industryIds: [32], careerUrl: 'https://book.zongheng.com/company/job.html', aliases: ['Zongheng Literature', '纵横文学'] },
  { name: '便利蜂商贸有限公司', industryIds: [14], careerUrl: 'https://app-tc.mokahr.com/apply/bianlifeng/4001?edit=1', aliases: ['Bianlifeng', '便利蜂'] },
  { name: '百望股份有限公司', industryIds: [9], careerUrl: 'https://web.baiwang.com/social-recruitment.html', aliases: ['Baiwang', '百望股份'] },
  { name: '北京中科金得助智能科技有限公司', industryIds: [3], careerUrl: 'https://www.zkj.com/join-us', aliases: ['Zhongguancun Kejin', '中关村科金'] },
  { name: '北京直真科技股份有限公司', industryIds: [9], careerUrl: 'https://www.zznode.com/job/', aliases: ['ZZNODE', '直真科技'] },
  { name: '北京千方科技股份有限公司', industryIds: [9], careerUrl: 'https://www.ctfo.com/aboutUs/joinUs', aliases: ['China TransInfo', '千方科技'] },
  { name: '京北方信息技术股份有限公司', industryIds: [9], careerUrl: 'https://www.northking.net/jrwm.html', aliases: ['Northking', '京北方'] },
  { name: '昆仑万维科技股份有限公司', industryIds: [1], careerUrl: 'https://jobs.kunlun.com/index', aliases: ['Kunlun', '昆仑万维'] },
  { name: '荣联科技集团股份有限公司', industryIds: [9], careerUrl: 'https://ronglian.zhiye.com/', aliases: ['Ronglian', '荣联科技'] },
  { name: '绿盟科技集团股份有限公司', industryIds: [9], careerUrl: 'https://www.nsfocus.com.cn/campus/3_1.html', aliases: ['NSFOCUS', '绿盟科技'] },
  { name: '北京第四范式智能技术股份有限公司', industryIds: [3], careerUrl: 'https://www.4paradigm.com/about/hr.html', aliases: ['4Paradigm', '第四范式'] },
  { name: '居然智家新零售集团股份有限公司', industryIds: [24], careerUrl: 'https://recruit.juran.com.cn/', aliases: ['Easyhome', '居然之家'] },
  { name: '北京搜房房天下网络技术有限公司', industryIds: [23], careerUrl: 'http://job.fang.com/index.html', aliases: ['Fang.com', '房天下', '搜房网'] },
  { name: '北京小马智行科技有限公司', industryIds: [19], careerUrl: 'https://campus.pony.ai/guideline', aliases: ['Pony.ai', '小马智行'] },
  { name: '北京极智嘉科技股份有限公司', industryIds: [8], careerUrl: 'https://www.geekplus.com/zh-hant/company/career', aliases: ['Geek+', '极智嘉'] },
  { name: '北京牛电科技有限责任公司', industryIds: [19], careerUrl: 'https://www.niu.com/about/join', aliases: ['NIU', '小牛电动'] },
  { name: '北京四方继保自动化股份有限公司', industryIds: [21], careerUrl: 'https://www.sf-auto.com/campus', aliases: ['Sifang', '四方继保'] },
  { name: '北京华峰测控技术股份有限公司', industryIds: [5], careerUrl: 'https://ewo56q2mqk.jobs.feishu.cn/929066', aliases: ['AccoTest', '华峰测控'] },
  { name: '泰康保险集团股份有限公司', industryIds: [13], careerUrl: 'https://jobtaikang.zhiye.com/campuslist', aliases: ['Taikang', '泰康'] },
  { name: '阳光保险集团股份有限公司', industryIds: [13], careerUrl: 'https://sunzhaopin.sinosig.com/', aliases: ['Sunshine Insurance', '阳光保险'] },
  { name: '天融信科技集团股份有限公司', industryIds: [9], careerUrl: 'https://topsec.zhiye.com/campus/jobs', aliases: ['Topsec', '天融信'] },
  { name: '北京恒华伟业科技股份有限公司', industryIds: [9], careerUrl: 'http://www.ieforever.com/class/view?id=37', aliases: ['Henghua', '恒华科技'] },
  { name: '北京易动纷享科技有限责任公司', industryIds: [9], careerUrl: 'https://www.fxiaoke.com/crm/about-join/', aliases: ['Fxiaoke', '纷享销客'] },
  { name: '北京仁科互动网络技术有限公司', industryIds: [4], careerUrl: 'https://neocrm.zhiye.com/', aliases: ['Neocrm', '销售易'] },
  { name: '北京金堤科技有限公司', industryIds: [9], careerUrl: 'https://job.tianyancha.com/', aliases: ['Tianyancha', '天眼查'] },
  { name: '北京淘友天下科技发展有限公司', industryIds: [1], careerUrl: 'https://maimai.jobs.feishu.cn/index/login', aliases: ['Maimai', '脉脉'] },
  { name: '北京蓝色光标数据科技股份有限公司', industryIds: [33], careerUrl: 'https://bluefocus.jobs.feishu.cn/index', aliases: ['BlueFocus', '蓝色光标'] },
  { name: '华扬联众数字技术股份有限公司', industryIds: [33], careerUrl: 'http://cn.hylinkdigital.com/job.html', aliases: ['Hylink', '华扬联众'] },
  { name: '乐元素科技（北京）股份有限公司', industryIds: [2], careerUrl: 'https://app.mokahr.com/campus_apply/leyuansu/2357', aliases: ['Happy Elements', '乐元素'] },
  { name: '北京东方国信科技股份有限公司', industryIds: [9], careerUrl: 'https://bonczp.zhiye.com/', aliases: ['BONC', '东方国信'] },
  { name: '北京世纪互联宽带数据中心有限公司', industryIds: [9], careerUrl: 'https://vnet.jobs.feishu.cn/index/', aliases: ['VNET', '世纪互联'] },
  { name: '北京华大九天科技股份有限公司', industryIds: [5], careerUrl: 'https://www.empyrean.com.cn/article/job-list-4.html', aliases: ['Empyrean', '华大九天'] },
  { name: '北京亿华通科技股份有限公司', industryIds: [20], careerUrl: 'http://www.sinohytec.com/recruit/shcool.html', aliases: ['SinoHytec', '亿华通'] },
  { name: '北京贝瑞和康生物技术有限公司', industryIds: [18], careerUrl: 'https://www.berrygenomics.com/cmscontent/166.html', aliases: ['Berry Genomics', '贝瑞基因'] },
  { name: '北京全式金生物技术股份有限公司', industryIds: [18], careerUrl: 'https://www.transgen.com/jobs.html', aliases: ['TransGen Biotech', '全式金'] },
  { name: '北京神州细胞生物技术集团股份公司', industryIds: [18], careerUrl: 'https://www.sinocelltech.com/Gather/job/pid/7.html', aliases: ['Sinocelltech', '神州细胞'] },
  { name: '首药控股（北京）股份有限公司', industryIds: [18], careerUrl: 'http://www.shouyaoholding.com/resources_details.php?act=idea&id=11', aliases: ['Shouyao Holdings', '首药控股'] },
  { name: '北京百普赛斯生物科技股份有限公司', industryIds: [18], careerUrl: 'https://careers.acrobiosystems.cn/', aliases: ['ACROBiosystems', '百普赛斯'] },
  { name: '北京春雨天下软件有限公司', industryIds: [17], careerUrl: 'https://www.chunyuyisheng.com/recruitment/position_list/', aliases: ['Chunyu Doctor', '春雨医生'] },
  { name: '中公教育科技股份有限公司', industryIds: [30], careerUrl: 'https://www.offcn.com/zg/zxns/', aliases: ['Offcn', '中公教育'] },
  { name: '中科软科技股份有限公司', industryIds: [9], careerUrl: 'https://sinosoft.com.cn/Joinus/beijing.html', aliases: ['Sinosoft', '中科软'] },
  { name: '北京中科金财科技股份有限公司', industryIds: [9], careerUrl: 'https://www.sinodata.net.cn/zh-cn/jobs', aliases: ['Sinodata', '中科金财'] },
  { name: '北京神州泰岳软件股份有限公司', industryIds: [4], careerUrl: 'https://www.ultrapower.com.cn/joinus/', aliases: ['Ultrapower', '神州泰岳'] },
  { name: '北京同有飞骥科技股份有限公司', industryIds: [8], careerUrl: 'https://www.toyou.com.cn/Tongyou/ShoolJoin/', aliases: ['NetStor', '同有科技'] },
  { name: '诺思格（北京）医药科技股份有限公司', industryIds: [18], careerUrl: 'https://www.rg-pharma.com/zhaopinpingtailianjie.html', aliases: ['R&G Pharma', '诺思格'] },
  { name: '快看世界（北京）科技有限公司', industryIds: [32], careerUrl: 'https://www.kuaikanmanhua.com/webs/join/us', aliases: ['Kuaikan Manhua', '快看漫画'] },
  { name: '北京亿心宜行汽车技术开发服务有限公司', industryIds: [26], careerUrl: 'https://h5.edaijia.cn/recruit/', aliases: ['eDaijia', 'e代驾'] },
  { name: '中科驭数（北京）科技有限公司', industryIds: [5], careerUrl: 'https://www.yusur.tech/about/joinus', aliases: ['YUSUR', '中科驭数'] },
  { name: '北京极客邦科技有限公司', industryIds: [32], careerUrl: 'https://www.geekbang.org/recruit/', aliases: ['Geekbang', '极客邦科技'] },
  { name: '北京长亭科技有限公司', industryIds: [9], careerUrl: 'https://join.chaitin.cn/plugins/career_site/sites/default', aliases: ['Chaitin', '长亭科技'] },
  { name: '北京明朝万达科技股份有限公司', industryIds: [9], careerUrl: 'http://wondersoft.cn/about/job.html', aliases: ['Wondersoft', '明朝万达'] },
  { name: '北京雪球信息科技有限公司', industryIds: [12], careerUrl: 'https://xueqiu.com/about/jobs', aliases: ['Xueqiu', '雪球'] },
  { name: '北京向上一心科技有限公司', industryIds: [12], careerUrl: 'https://tigertech.jobs.feishu.cn/index', aliases: ['Tiger Brokers', '老虎国际'] },
  { name: '北京青云科技股份有限公司', industryIds: [4], careerUrl: 'https://www.qingcloud.com/jobs', aliases: ['QingCloud', '青云'] },
  { name: '中软国际有限公司', industryIds: [9], careerUrl: 'https://www.chinasofti.com/pages/careers/index.html', aliases: ['Chinasoft International', '中软国际'] },
  { name: '广联达科技股份有限公司', industryIds: [4], careerUrl: 'https://campus.glodon.com/', aliases: ['Glodon', '广联达'] },
  { name: '北京东方雨虹防水技术股份有限公司', industryIds: [22], careerUrl: 'https://yuhongzp.zhiye.com/', aliases: ['Oriental Yuhong', '东方雨虹'] },
  { name: '北京北信源软件股份有限公司', industryIds: [9], careerUrl: 'http://www.vrv.com.cn/join-57.html', aliases: ['VRV', '北信源'] },
  { name: '北京海天瑞声科技股份有限公司', industryIds: [3], careerUrl: 'https://www.haitianruisheng.com/?m=index&c=aboutus&a=saferjoin&catid=40', aliases: ['Haitian Ruisheng', '海天瑞声'] },
  { name: '北京云中融信网络科技股份有限公司', industryIds: [9], careerUrl: 'https://a5bq662kv5.jobs.feishu.cn/index', aliases: ['RongCloud', '融云'] },
  { name: '北京思特奇信息技术股份有限公司', industryIds: [9], careerUrl: 'https://www.si-tech.com.cn/pub-page/talents.html', aliases: ['SI-TECH', '思特奇'] },
  { name: '特斯拉', industryIds: [19], careerUrl: 'https://app.mokahr.com/social-recruitment/tesla/46129?locale=zh-CN#/', aliases: ['Tesla', 'Tesla China'] },
  { name: '苹果', industryIds: [6], careerUrl: 'https://jobs.apple.com/zh-cn/search?location=china', aliases: ['Apple', 'Apple China'] },
  { name: '博世', industryIds: [21], careerUrl: 'https://bosch.com.cn/careers/job-offers/', aliases: ['Bosch', '博世中国'] },
  { name: '西门子', industryIds: [21], careerUrl: 'https://jobs.siemens.com/zh_CN/externaljobs', aliases: ['Siemens', '西门子中国'] },
  { name: '大众汽车集团（中国）', industryIds: [19], careerUrl: 'https://volkswagengroupchina.jobs2web.sapsf.cn/go/Career-Site-Home-Page-CN/5466330/', aliases: ['Volkswagen Group China', '大众中国'] },
  { name: '巴斯夫', industryIds: [22], careerUrl: 'https://basf.jobs/search?locale=en_US&skillsSearch=false&markerViewed=&carouselIndex=&facetFilters=%7B%22jobLocationCountry%22%3A%5B%22China%22%5D%7D&pageNumber=0', aliases: ['BASF', '巴斯夫中国'] },
  { name: '德勤中国', industryIds: [35], careerUrl: 'https://www.deloitte.com/cn/zh/cn-careers.html', aliases: ['Deloitte China', '德勤'] },
  { name: '安永中国', industryIds: [35], careerUrl: 'https://www.ey.com/zh_cn/careers', aliases: ['EY China', '安永'] },
  { name: '毕马威中国', industryIds: [35], careerUrl: 'https://kpmg.com/cn/zh/careers.html', aliases: ['KPMG China', '毕马威'] },
  { name: '埃森哲', industryIds: [35], careerUrl: 'https://www.accenture.com/cn-zh/careers', aliases: ['Accenture', '埃森哲中国'] },
  { name: '强生', industryIds: [17], careerUrl: 'https://www.careers.jnj.com/en/', aliases: ['Johnson & Johnson', 'J&J'] },
  { name: '默沙东', industryIds: [18], careerUrl: 'https://jobs.msd.com/cn/zh', aliases: ['MSD', 'Merck', '默克'] },
  { name: '梅赛德斯-奔驰', industryIds: [19], careerUrl: 'https://group.mercedes-benz.com/careers/', aliases: ['Mercedes-Benz', '奔驰'] },
  { name: 'ABB', industryIds: [21], careerUrl: 'https://careers.abb/global/en/search-results?country=China', aliases: ['ABB China', 'ABB集团'] },
  { name: '陶氏公司', industryIds: [22], careerUrl: 'https://corporate.dow.com/en-us/careers.html', aliases: ['Dow', '陶氏化学'] },
  { name: '杜邦', industryIds: [22], careerUrl: 'https://careers.dupont.com/us/en', aliases: ['DuPont', '杜邦中国'] },
  { name: '索尼', industryIds: [8], careerUrl: 'https://www.sony.com/en/SonyInfo/Careers/', aliases: ['Sony', 'Sony China'] },
  { name: '麦肯锡', industryIds: [35], careerUrl: 'https://www.mckinsey.com/careers/search-jobs', aliases: ['McKinsey', 'McKinsey & Company'] },
  { name: '波士顿咨询', industryIds: [35], careerUrl: 'https://careers.bcg.com/global/en', aliases: ['BCG', 'Boston Consulting Group'] },
  { name: '贝恩公司', industryIds: [35], careerUrl: 'https://www.bain.com/careers/', aliases: ['Bain & Company', 'Bain'] },
  { name: '罗兰贝格', industryIds: [35], careerUrl: 'https://www.rolandberger.com/en/Join/Join-Us/Overview/', aliases: ['Roland Berger', '罗兰贝格咨询'] },
  { name: '奥纬咨询', industryIds: [35], careerUrl: 'https://www.oliverwyman.com/careers.html', aliases: ['Oliver Wyman', '奥纬'] },
  { name: '罗氏', industryIds: [18], careerUrl: 'https://careers.roche.com/global/en/search-results?keywords=China', aliases: ['Roche', '罗氏中国'] },
  { name: '诺华', industryIds: [18], careerUrl: 'https://www.novartis.com/careers', aliases: ['Novartis', '诺华中国'] },
  { name: '阿斯利康', industryIds: [18], careerUrl: 'https://careers.astrazeneca.com/search-jobs/china/7684/1', aliases: ['AstraZeneca', '阿斯利康中国'] },
  { name: '葛兰素史克', industryIds: [18], careerUrl: 'https://jobs.gsk.com/en-gb/search-results?keywords=China', aliases: ['GSK', 'GlaxoSmithKline'] },
  { name: '辉瑞', industryIds: [18], careerUrl: 'https://www.pfizer.com/about/careers', aliases: ['Pfizer', '辉瑞中国'] },
  { name: '拜耳', industryIds: [18], careerUrl: 'https://www.bayer.com/en/career', aliases: ['Bayer', '拜耳中国'] },
  { name: '礼来', industryIds: [18], careerUrl: 'https://careers.lilly.com/us/en', aliases: ['Eli Lilly', 'Lilly'] },
  { name: '阿迪达斯', industryIds: [15], careerUrl: 'https://careers.adidas-group.com/', aliases: ['adidas', 'Adidas China'] },
  { name: '马士基', industryIds: [25], careerUrl: 'https://www.maersk.com/careers/', aliases: ['Maersk', 'A.P. Moller - Maersk'] },
  { name: '耐克', industryIds: [15], careerUrl: 'https://careers.nike.com/zh-cn/', aliases: ['Nike', 'Nike China'] },
  { name: '玛氏', industryIds: [16], careerUrl: 'https://careers.mars.com/global/en/search-results?keywords=China', aliases: ['Mars', 'Mars China'] },
  { name: '赛诺菲', industryIds: [18], careerUrl: 'https://jobs.sanofi.com/en/', aliases: ['Sanofi', '赛诺菲中国'] },
  { name: '3M', industryIds: [22], careerUrl: 'https://www.3m.com/3M/en_US/careers-us/', aliases: ['3M中国', 'Minnesota Mining and Manufacturing'] },
  { name: '康宁', industryIds: [22], careerUrl: 'https://www.corning.com/worldwide/en/careers.html', aliases: ['Corning', '康宁中国'] },
  { name: '联邦快递', industryIds: [25], careerUrl: 'https://careers.fedex.com/zh-cn', aliases: ['FedEx', 'FedEx China'] },
  { name: '空中客车', industryIds: [27], careerUrl: 'https://www.airbus.com/en/careers', aliases: ['Airbus', '空客'] },
  { name: '波音', industryIds: [27], careerUrl: 'https://jobs.boeing.com/', aliases: ['Boeing', '波音中国'] },
  { name: '壳牌', industryIds: [28], careerUrl: 'https://www.shell.com/careers.html', aliases: ['Shell', 'Shell China'] },
  { name: '英国石油', industryIds: [28], careerUrl: 'https://careers.bp.com/', aliases: ['bp', 'BP China'] },
  { name: '迪士尼', industryIds: [32], careerUrl: 'https://www.disneycareers.com/en', aliases: ['Disney', 'The Walt Disney Company'] },
  { name: '思科', industryIds: [7], careerUrl: 'https://careers.cisco.com/global/en', aliases: ['Cisco', 'Cisco China'] },
  { name: 'DHL', industryIds: [25], careerUrl: 'https://careers.dhl.com/global/en', aliases: ['DHL Group', '敦豪'] },
  { name: '三星电子', industryIds: [8], careerUrl: 'https://www.samsung.com.cn/about-us/careers/', aliases: ['Samsung', 'Samsung Electronics China'] },
  { name: '惠普', industryIds: [6], careerUrl: 'https://jobs.hp.com/', aliases: ['HP', 'Hewlett-Packard'] },
  { name: 'LVMH', industryIds: [15], careerUrl: 'https://www.lvmh.com/en/join-us/work-at-lvmh', aliases: ['LVMH集团', '路威酩轩'] },
  { name: '亿滋国际', industryIds: [16], careerUrl: 'https://www.mondelezinternational.com/careers/', aliases: ['Mondelēz International', '亿滋'] },
  { name: '科沃斯', industryIds: [6], careerUrl: 'https://hr.ecovacs.cn/', aliases: ['ECOVACS', '科沃斯机器人'] },
  { name: '微众银行', industryIds: [11], careerUrl: 'https://hr.webank.com/apply/webankhr/68/#/', aliases: ['WeBank', '深圳前海微众银行'] },
  { name: '贝壳找房', industryIds: [23], careerUrl: 'https://job.ke.com/', aliases: ['KE Holdings', 'Beike', '贝壳'] },
  { name: '易车', industryIds: [19], careerUrl: null, aliases: ['Yiche', '易车网'] },
  { name: '转转', industryIds: [14], careerUrl: null, aliases: ['Zhuanzhuan'] },
  { name: '好大夫在线', industryIds: [17], careerUrl: null, aliases: ['Haodf', '好大夫'] },
  { name: '轻松集团', industryIds: [17], careerUrl: null, aliases: ['Qingsong Group', '轻松筹'] },
  { name: '本来生活', industryIds: [14], careerUrl: null, aliases: ['Benlai', '本来生活网'] },
  { name: '映客', industryIds: [32], careerUrl: null, aliases: ['Inke', '映客直播'] },
  { name: '拉勾', industryIds: [37], careerUrl: 'https://www.lagou.com/about/jobs', aliases: ['Lagou', '拉勾招聘'] },
  { name: '融360', industryIds: [10], careerUrl: null, aliases: ['Rong360'] },
  { name: '中文在线', industryIds: [32], careerUrl: null, aliases: ['COL', '中文在线集团'] },
  { name: '视觉中国', industryIds: [32], careerUrl: null, aliases: ['Visual China', 'VCG'] },
  { name: '量子之歌', industryIds: [30], careerUrl: null, aliases: ['Quantasing', '量子之歌集团'] },
  { name: '优信', industryIds: [19], careerUrl: null, aliases: ['Uxin'] },
  { name: '国双科技', industryIds: [9], careerUrl: null, aliases: ['Gridsum', '国双'] },
  { name: '神州信息', industryIds: [9], careerUrl: null, aliases: ['SinoSoft', '神州信息技术'] },
  { name: '汉王科技', industryIds: [8], careerUrl: null, aliases: ['Hanvon', '汉王'] },
  { name: '石基信息', industryIds: [9], careerUrl: null, aliases: ['Shiji', '石基'] },
  { name: '极客时间', industryIds: [30], careerUrl: null, aliases: ['Geekbang', '极客邦'] },
  { name: '果壳', industryIds: [32], careerUrl: null, aliases: ['Guokr'] },
  { name: '青藤云安全', industryIds: [9], careerUrl: null, aliases: ['Eversafe', '青藤'] },
  { name: '美菜网', industryIds: [14], careerUrl: null, aliases: ['Meicai', '美菜'] },
  { name: '一点资讯', industryIds: [32], careerUrl: null, aliases: ['Yidian', '一点'] },
  { name: '58同城', industryIds: [14], careerUrl: null, aliases: ['58.com', '五八同城'] },
  { name: '自如', industryIds: [23], careerUrl: null, aliases: ['Ziroom', '自如网'] },
  { name: '我爱我家', industryIds: [23], careerUrl: null, aliases: ['5i5j', '我爱我家集团'] },
  { name: '麦田房产', industryIds: [23], careerUrl: null, aliases: ['Maitian', '麦田'] },
  { name: '拉卡拉', industryIds: [10], careerUrl: null, aliases: ['Lakala', '拉卡拉支付'] },
  { name: '亚信科技', industryIds: [9], careerUrl: null, aliases: ['AsiaInfo', '亚信'] },
  { name: '博彦科技', industryIds: [9], careerUrl: null, aliases: ['Beyondsoft', '博彦'] },
  { name: '经纬恒润', industryIds: [19], careerUrl: null, aliases: ['Hirain', '经纬恒润科技'] },
  { name: '玻色量子', industryIds: [3], careerUrl: null, aliases: ['Origin Quantum', '玻色量子科技'] },
  { name: '中关村在线', industryIds: [32], careerUrl: null, aliases: ['ZOL', 'ZOL中关村在线'] },
  { name: 'IT168', industryIds: [32], careerUrl: null, aliases: ['IT168.com'] },
  { name: '混沌学园', industryIds: [30], careerUrl: null, aliases: ['Hundun', '混沌大学'] },
  { name: '甲子光年', industryIds: [32], careerUrl: null, aliases: ['Jazzyear', '甲子光年智库'] },
  { name: '中科江南', industryIds: [9], careerUrl: null, aliases: ['Galaxy Fintech', '中科江南信息技术'] },
  { name: '迪信通', industryIds: [14], careerUrl: null, aliases: ['Dixintong', '迪信通科技'] },
  { name: '恒安嘉新', industryIds: [9], careerUrl: null, aliases: ['Hengan Jiaxin', '恒安嘉新科技'] },
  { name: '安博通', industryIds: [9], careerUrl: null, aliases: ['Abt Network', '安博通科技'] },
  { name: '百融云创', industryIds: [10], careerUrl: null, aliases: ['Bairong', '百融'] },
  { name: '智联招聘', industryIds: [37], careerUrl: null, aliases: ['Zhaopin', '智联'] },
  { name: '猎聘', industryIds: [37], careerUrl: null, aliases: ['Liepin', '猎聘网'] },
  { name: '科蓝软件', industryIds: [9], careerUrl: null, aliases: ['Kelan Software', '科蓝'] },
  { name: '爱康国宾', industryIds: [17], careerUrl: null, aliases: ['iKang', '爱康'] },
  { name: '镁伽机器人', industryIds: [6], careerUrl: null, aliases: ['Megarobo', '镁伽'] },
  { name: '银河航天', industryIds: [27], careerUrl: null, aliases: ['GalaxySpace', '银河航天科技'] },
  { name: '探路者', industryIds: [15], careerUrl: null, aliases: ['Toread', '探路者集团'] },
  { name: '碧生源', industryIds: [16], careerUrl: null, aliases: ['Besunyen', '碧生源控股'] },
  { name: '格灵深瞳', industryIds: [3], careerUrl: null, aliases: ['Deep Glint', '格灵深瞳科技'] },
  { name: '海致科技', industryIds: [9], careerUrl: null, aliases: ['Haizhi', '海致'] },
]
